### PR TITLE
Fix stackoverflow from unimplemented method in item stack

### LINKED ISSUE #1268: StackOverflowError on calling displayName() on ItemStack
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [x] I am using the latest version of MockBukkit.

### Minecraft Version

1.21

### Describe the bug

Calling the method displayName() on ItemStack results in an infinite loop.
```
java.lang.StackOverflowError
	at org.bukkit.inventory.ItemStack.displayName(ItemStack.java:712)
	at org.mockbukkit.mockbukkit.inventory.ItemFactoryMock.displayName(ItemFactoryMock.java:231)
	at org.bukkit.inventory.ItemStack.displayName(ItemStack.java:712)
	at org.mockbukkit.mockbukkit.inventory.ItemFactoryMock.displayName(ItemFactoryMock.java:231)
	at org.bukkit.inventory.ItemStack.displayName(ItemStack.java:712)
	at org.mockbukkit.mockbukkit.inventory.ItemFactoryMock.displayName(ItemFactoryMock.java:231)
	at org.bukkit.inventory.ItemStack.displayName(ItemStack.java:712)
	at org.mockbukkit.mockbukkit.inventory.ItemFactoryMock.displayName(ItemFactoryMock.java:231)
	at org.bukkit.inventory.ItemStack.displayName(ItemStack.java:712)
	at org.mockbukkit.mockbukkit.inventory.ItemFactoryMock.displayName(ItemFactoryMock.java:231)
	at org.bukkit.inventory.ItemStack.displayName(ItemStack.java:712)
	at org.mockbukkit.mockbukkit.inventory.ItemFactoryMock.displayName(ItemFactoryMock.java:231)
	at org.bukkit.inventory.ItemStack.displayName(ItemStack.java:712)
	at org.mockbukkit.mockbukkit.inventory.ItemFactoryMock.displayName(ItemFactoryMock.java:231)
....
```

### Reproducible Test

```java
  @Test
  public void callItemStackDisplayName() {
      var itemStack = new ItemStack(Material.DIAMOND_SWORD);
      itemStack.displayName();
  }
```

### Anything else?

Paper API Version 1.21.1 and newest MockBukkit v4.27.0

### PR DESCRIPTION
**Pull request by Thorinwasher**
# Description

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

### CODE REVIEW

**Comment by Thorinwasher** [comment]
Fixes #1268

File: src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java [hunk 1]
```diff
@@ -687,4 +690,27 @@ void removeEnchantments()
...
+		Component displayName1 = item.displayName();
+		assertNotNull(displayName1);
+		assertEquals("[Diamond Pickaxe]", PlainTextComponentSerializer.plainText().serialize(displayName1));
+		ItemMeta meta = item.getItemMeta();
+		meta.customName(Component.text("Hello world!"));
+		item.setItemMeta(meta);
+		Component displayName2 = item.displayName();
+		assertNotNull(displayName2);
+		assertNotEquals(displayName1, displayName2);
+		assertEquals("[Hello world!]", PlainTextComponentSerializer.plainText().serialize(displayName2));
```
Comment (4everTheOne) [inline src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java:713]: Are this brackets normal?

**Review by 4everTheOne — APPROVED** [review]

File: src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java (hunk 1 above)
Comment (Thorinwasher) [reply src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java:713]: I mostly guessed that from the code in paper. But, yeah probably a good idea to doube check that against a real instance

Comment (Thorinwasher) [reply src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java:713]: @4everTheOne Yep. I just tested this, and this is the case. So the test is correct
