### PR TITLE
Fixed Chest Inventory State not being updated in test

### LINKED ISSUE #1293: Chest Inventory State not being updated in test
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [x] I am using the latest version of MockBukkit.

### Minecraft Version

1.21

### Describe the bug

MockBukkit version: `4.33.2`
Last working version: `4.14.1`

Chest Inventory State does not get updated during a test. When debugging, it seems that all inventory items are `null`.

See screenshots of states of inventory when at the same line in the debugger in the versions:

`4.14.1`:

Image

`4.14.2`:

Image

### Reproducible Test

I have created a branch in my plugin repo to reproduce this.

https://github.com/stefan-cooper/SpigotUHC on branch `MockBukkit@4.33.2`.

If you run the test suite: `UHCLootTest`, you should be able to reproduce the bug.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by 4everTheOne**
# Description
This issue resolves #1293. The issue here was the method `createInventoryCopy`.

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

### CODE REVIEW

File: src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java [hunk 1]
```diff
@@ -55,48 +53,18 @@ protected ContainerStateMock(@NotNull Block block)
 	protected ContainerStateMock(@NotNull ContainerStateMock state)
 	{
 		super(state);
```
Comment (Thorinwasher) [inline src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java:55]: It's a state, it should copy the inventory. I want to be sure this behavior is the case by directly confirming against a paper server instance.

**Review by Thorinwasher — DISMISSED** [review]

File: src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java (hunk 1 above)
Comment (4everTheOne) [reply src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java:55]: Yes that's the case. I have added the following code to a class in `MetaMiner`to validate that and no exception was thrown:
```java
World world = Bukkit.getWorlds().get(0);
world.getBlockAt(0, 64, 0).setType(Material.CHEST);

var chestState = (Chest) world.getBlockAt(0, 64, 0).getState();
chestState.getBlockInventory().clear();
if (chestState.getBlockInventory().contains(ItemStack.of(Material.DIAMOND)))
{
	throw new IllegalStateException("The chest contains a diamond");
}

var chestState2 = (Chest) world.getBlockAt(0, 64, 0).getState();
chestState2.getBlockInventory().addItem(ItemStack.of(Material.DIAMOND));
if (!chestState.getBlockInventory().contains(ItemStack.of(Material.DIAMOND)))
{
	throw new IllegalStateException("The chest does not contain a diamond");
}
```
With this i also found something that i have to double check, in the method `getSnapshotInventory`. When this method is called, no change should be done to the original block. I'll add unit tests to validate this use case
```java
world.getBlockAt(0, 70, 0).setType(Material.CHEST);

var snapshotState = (Chest) world.getBlockAt(0, 70, 0).getState();
snapshotState.getSnapshotInventory().clear();
if (snapshotState.getSnapshotInventory().contains(ItemStack.of(Material.DIAMOND)))
{
	throw new IllegalStateException("The chest contains a diamond");
}

var snapshotState2 = (Chest) world.getBlockAt(0, 70, 0).getState();
snapshotState2.getSnapshotInventory().addItem(ItemStack.of(Material.DIAMOND));
if (snapshotState.getSnapshotInventory().contains(ItemStack.of(Material.DIAMOND)))
{
	throw new IllegalStateException("The chest contains a diamond");
}
```

**Comment by 4everTheOne** [comment]
Confirmed, the behavior matches the paper implementation, and more unit tests were added

File: src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java (hunk 1 above)
Comment (Thorinwasher) [reply src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java:55]: > Yes that's the case. I have added the following code to a class in MetaMinerto validate that and no exception was thrown:

Alright, if thats the case with this kind of tests on a paper server, then this pr seems correct. Sorry, I thought block states were proper **states**, but yes there's always exceptions in pretty much anything.

**Review by Thorinwasher — APPROVED** [review]
