### PR TITLE
Fixed serialization of ItemStackMirrorMock

### LINKED ISSUE #1449: ItemStackMirror not registered in ConfigurationSerializable
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [x] I am using the latest version of MockBukkit.

### Minecraft Version

1.21

### Describe the bug

The new updates make use of `ItemStackMirror` instead of `ItemStackMock` which changes how the ItemStack is serialized. I thinkkk? this can be solved with `@DelegateDeserialization(ItemStack.class)` annotation on `ItemStackMirror` class.

### Reproducible Test

Logs: https://pastes.dev/DEIFaEtTj2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by 4everTheOne**
# Description

Fixes serialization of ItemStackMirrorMock so that it emulates the real serialization.
Fixes https://github.com/MockBukkit/MockBukkit/issues/1449.

# Checklist

The following items should be checked before the pull request can be merged.

- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

### CODE REVIEW

File: src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMirrorTest.java [hunk 1]
```diff
@@ -60,4 +69,40 @@ void givenAnyChangeExecutedInTheMirrorItem_ShouldBeAppliedInTheOriginal()
 
 	}
 
+	@Test
+	void classHasDelegateSerializationAnnotation()
+	{
+		DelegateDeserialization delegateDeserialization = ItemStackMirror.class.getAnnotation(DelegateDeserialization.class);
+		assertNotNull(delegateDeserialization, "The class should be annotated with @DelegateDeserialization(ItemStack.class)");
+		assertEquals(ItemStack.class, delegateDeserialization.value());
+	}
```
Comment (Thorinwasher) [inline src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMirrorTest.java]: This is more of a test on the Java compiler, from my point of view at least. I guess you could argue that this promotes stability for the code, as it now has more friction to remove this annotation, but I also think that this is going to be the case anyhow:
> Don't touch code unless necessary, things will break

**Review by Thorinwasher — COMMENTED** [review]
Looks good to me, just one comment on one test

**Review by Thorinwasher — APPROVED** [review]
