### PR TITLE
Fixed incorret getDataAsString for Door and Bisected

### LINKED ISSUE #1433: BlockData#getAsString() returns incorrect value
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [x] I am using the latest version of MockBukkit.

### Minecraft Version

1.21

### Describe the bug

The string returned by `BlockData.getAsString(false)` is incorrect. 

### Reproducible Test

For example, try
```
Material.BAMBOO_DOOR.createBlockData().getAsString(false)
```

This should return `minecraft:bamboo_door[facing=north,half=lower,hinge=left,open=false,powered=false]` but instead returns `minecraft:bamboo_door[facing=north,half=bottom,hinge=left,open=false,powered=false]`. Other similar blocks with two parts have the same issue.

half=bottom -> half=lower
half=top -> half=upper

### Anything else?

List of blocks this issue occurs for
```
StateType Mapping Errors:
State type mismatch for material BAMBOO_DOOR, type=air, value=bamboo_door
State type mismatch for material DARK_OAK_DOOR, type=air, value=dark_oak_door
State type mismatch for material WAXED_EXPOSED_COPPER_DOOR, type=air, value=waxed_exposed_copper_door
State type mismatch for material ACACIA_DOOR, type=air, value=acacia_door
State type mismatch for material OAK_DOOR, type=air, value=oak_door
State type mismatch for material IRON_DOOR, type=air, value=iron_door
State type mismatch for material WEATHERED_COPPER_DOOR, type=air, value=weathered_copper_door
State type mismatch for material LILAC, type=air, value=lilac
State type mismatch for material PITCHER_PLANT, type=air, value=pitcher_plant
State type mismatch for material CRIMSON_DOOR, type=air, value=crimson_door
State type mismatch for material LARGE_FERN, type=air, value=large_fern
State type mismatch for material PALE_OAK_DOOR, type=air, value=pale_oak_door
State type mismatch for material COPPER_DOOR, type=air, value=copper_door
State type mismatch for material JUNGLE_DOOR, type=air, value=jungle_door
State type mismatch for material SPRUCE_DOOR, type=air, value=spruce_door
State type mismatch for material WAXED_COPPER_DOOR, type=air, value=waxed_copper_door
State type mismatch for material SUNFLOWER, type=air, value=sunflower
State type mismatch for material BIRCH_DOOR, type=air, value=birch_door
State type mismatch for material PEONY, type=air, value=peony
State type mismatch for material MANGROVE_DOOR, type=air, value=mangrove_door
State type mismatch for material WAXED_WEATHERED_COPPER_DOOR, type=air, value=waxed_weathered_copper_door
State type mismatch for material ROSE_BUSH, type=air, value=rose_bush
State type mismatch for material WAXED_OXIDIZED_COPPER_DOOR, type=air, value=waxed_oxidized_copper_door
State type mismatch for material CHERRY_DOOR, type=air, value=cherry_door
State type mismatch for material TALL_SEAGRASS, type=air, value=tall_seagrass
State type mismatch for material WARPED_DOOR, type=air, value=warped_door
State type mismatch for material OXIDIZED_COPPER_DOOR, type=air, value=oxidized_copper_door
State type mismatch for material EXPOSED_COPPER_DOOR, type=air, value=exposed_copper_door
State type mismatch for material TALL_GRASS, type=air, value=tall_grass
```

### PR DESCRIPTION
**Pull request by 4everTheOne**
# Description
Fixes https://github.com/MockBukkit/MockBukkit/issues/1433

# Checklist

The following items should be checked before the pull request can be merged.

- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

### CODE REVIEW

File: src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java [hunk 1]
```diff
@@ -76,6 +76,13 @@ public enum BlockDataKey
 	 * Stores what {@link Bisected.Half} a {@link Bisected} block is placed in.
 	 */
 	HALF("half", string -> Bisected.Half.valueOf(string.toUpperCase(Locale.ROOT)), Bisected.class::isInstance),
+	/**
+	 * Stores what {@link Bisected.Half} a {@link Bisected} block is placed in.
+	 * Similar to HALF but stores the value as lower or upper.
+	 *
+	 * @see BisectedDataMock
+	 */
+	HALF_RAW("half", a -> a, Bisected.class::isInstance),
```
Comment (Thorinwasher) [inline src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java]: An alternative to this is to do this, where isOneBlockStructure is annotaded Internal, and HalfSerdes is a serializer / deserializer. 
```suggestion
	HALF_SINGLE_BLOCK("half", new HalfSerdes(true), object -> object instanceof BisectedMock bisected && bisected.isOneBlockStructure()),
	/**
	 * Stores what {@link Bisected.Half} a {@link Bisected} block is placed in.
	 * Similar to HALF but stores the value as lower or upper.
	 *
	 * @see BisectedDataMock
	 */
	HALF_MULTI_BLOCK("half", new HalfSerdes(false), object -> object instanceof BisectedMock bisected && !bisected.isOneBlockStructure()),
```
I guess this would need a bit more work, but from my point of view, more consistent with the current way things are done. What do you think? Am I over-complicating things as usual?

Comment (4everTheOne) [reply src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java]: Makes total sense, thanks for the suggestion. I will update that ☺️

Comment (4everTheOne) [reply src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java]: I need to validate how am i going to check the `isOneBlockStructure` because using the classes directly we don't have this type of information yet

Comment (4everTheOne) [reply src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java]: @Thorinwasher , i have proposed a new method in PaperMC to help with this at https://github.com/PaperMC/Paper/pull/13087. I think with this approach it's easier for developers to identify the bisect type and for us would be transparent. If you agree with the approach, i would say that we can progress with this PR and when the new method is available i will update the validations.

Comment (Thorinwasher) [reply src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java]: Oh, I was just thinking it could be refering to a a hashset of materials or something, nothing that grandiose. Or something you could use with metaminer

**Comment by 4everTheOne** [comment]
I've added a method to validate if the block is single or not, and included more unit tests for the get as string using the metaminer

**Review by Thorinwasher — APPROVED** [review]
