### PR TITLE
Fix ServerMock#getBukkitVersion not returning the full version

### LINKED ISSUE #543: Value of `getBukkitVersion()` is nonstandard
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.19

### Describe the bug

The value of `Bukkit.getBukkitVersion()` does not conform to the expected format containing a revision number and a snapshot qualifier.

### Reproducible Test

Compile this MWE using your tool of choice:

```java
package net.ssterling.example;

import org.bukkit.Bukkit;
import be.seeseemelk.mockbukkit.MockBukkit;
import be.seeseemelk.mockbukkit.ServerMock;

class ServerVersionTest
{
	public static void main(String[] args)
	{
		ServerMock server = MockBukkit.mock();
		String version_string = Bukkit.getBukkitVersion();
		System.out.println("Bukkit API version: " + version_string);
		MockBukkit.unmock();
	}
}
```

The output is `1.19`, not the expected `1.19-R0.1-SNAPSHOT`.

### Anything else?

I’m currently working on a utility to more easily process Bukkit API and vanilla Minecraft version strings.
I’m using MockBukkit for unit tests; one of those tests makes sure the value of `Bukkit.getBukkitVersion()` is correctly detected as a valid Bukkit API server string, making sure I didn’t accidentally screw up the regex.
You can see why the “server” itself providing an incorrect string is a problem for me.

I’d provide a link to the source for the project in question for context, but it’s still a pre-0.1.0 WIP.

### PR DESCRIPTION
**Pull request by Insprill**
# Description
Fixes the non-standard output of `ServerMock#getBukkitVersion`.
Also added tests to ensure this, and `ServerMock#getMinecraftVersion` return something matching the correct pattern.

Closes #543.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

### CODE REVIEW

File: src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java [hunk 1]
```diff
@@ -183,6 +183,24 @@ void getBukkitVersion_NotNull()
 		assertNotNull(server.getBukkitVersion());
 	}
 
+	@Test
+	void getBukkitVersion_CorrectPattern()
+	{
+		assertTrue(server.getBukkitVersion().matches("1\\.[0-9]+(\\.[0-9]+)?-R[0-9].[0-9]-SNAPSHOT"));
```
Comment (thelooter) [inline src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java]: According to https://www.regexplained.co.uk/ This doesn't seem to match for Dots

File: src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java [hunk 2]
```diff
@@ -183,6 +183,24 @@ void getBukkitVersion_NotNull()
...
+	@Test
+	void getMinecraftVersion_NotNull()
+	{
+		assertNotNull(server.getMinecraftVersion());
+	}
+
+	@Test
+	void getMinecraftVersion_CorrectPattern()
+	{
+		assertTrue(server.getMinecraftVersion().matches("1\\.[0-9]+(\\.[0-9]+)?"));
```
Comment (thelooter) [inline src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java:201]: According to https://www.regexplained.co.uk/ this doesn't seem to match for dots

File: src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java (hunk 1 above)
Comment (Insprill) [reply src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java]: It does match otherwise the test would not pass. If you copy it directly from the string you have to remove the extra backslash before the dots when putting it into a regex validator.

File: src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java (hunk 2 above)
Comment (Insprill) [reply src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java:201]: It does match otherwise the test would not pass. If you copy it directly from the string you have to remove the extra backslash before the dots when putting it into a regex validator.

File: src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java (hunk 1 above)
Comment (ssterling) [inline src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java]: If you browse the [SpigotMC Nexus repository](//hub.spigotmc.org/nexus/#view-repositories;snapshots~browsestorage), you’ll see that revision numbers aren’t mandatory, such as in `1.14.3-pre4-SNAPSHOT`.

**Review by ssterling — CHANGES_REQUESTED** [review]
Regex might not match certain future versions; Bukkit devs are somewhat inconsistent with whether they attach a revision number.

File: src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java (hunk 1 above)
Comment (Insprill) [reply src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java]: Perhaps ignoring what's between the Minecraft version and SNAPSHOT (and maybe after?) would be better?

Comment (ssterling) [reply src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java]: I didn’t even catch the `-pre4`, so yeah, I agree.

**Review by thelooter — APPROVED** [review]
